name: "Build Ark GNU/Linux"
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Ark GNU/Linux
    runs-on: ubuntu-latest
    container:
      image: docker.io/archlinux:latest
      options: --privileged
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git base-devel archiso arch-install-scripts curl reflector
      - name: Setup Git
        run: |
          git config --global user.name ${{ github.repository_owner }}
          git config --global user.email ${{ github.repository_owner }}@users.noreply.github.com
          git config --global pull.rebase false
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build Ark GNU/Linux
        run: |
          mv arklinux/airootfs/etc/pacman.d/mirrorlist arklinux/airootfs/etc/pacman.d/mirrorlist.old
          reflector --verbose --protocol https --latest 5 --sort rate --save arklinux/airootfs/etc/pacman.d/mirrorlist
          sed -i '/^\[options\]/a XferCommand = /usr/bin/curl -C - -f --retry 5 --retry-delay 1 --retry-max-time 60 %u -o %o' arklinux/airootfs/etc/pacman.conf
          sed -i 's/^\(ParallelDownloads = \)/#\1/' arklinux/airootfs/etc/pacman.conf
          mkarchiso -v -w arklinuxcache -o arklinuxbuild arklinux
      - name: Upload ISO
        uses: actions/upload-artifact@v3
        with:
          name: arklinux-latest-unstable.iso
          path: arklinuxbuild/arklinux-*.iso
